-- 코드를 입력하세요
SELECT YEAR(O.SALES_DATE) AS YEAR,
    MONTH(O.SALES_DATE) AS MONTH,
    U.GENDER AS GENDER,
    COUNT(DISTINCT U.USER_ID) AS USERS
FROM ONLINE_SALE O
LEFT JOIN USER_INFO U
ON O.USER_ID = U.USER_ID
WHERE U.GENDER is not null
GROUP BY MONTH,U.GENDER
ORDER BY YEAR ASC, MONTH ASC, GENDER ASC;