-- 코드를 입력하세요
SELECT c.CAR_ID,
    c.CAR_TYPE,
    (c.DAILY_FEE - ROUND(c.DAILY_FEE / 100 * p.DISCOUNT_RATE))*30
    AS FEE
FROM CAR_RENTAL_COMPANY_CAR c
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN p
    ON c.CAR_TYPE = p.CAR_TYPE 
WHERE c.CAR_TYPE IN ('세단','SUV') 
    AND c.CAR_ID NOT IN (
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE END_DATE >= '2022-11-01' AND START_DATE <= '2022-11-30'
    )
    AND p.DURATION_TYPE = '30일 이상'
HAVING FEE >= 500000 AND FEE < 2000000
ORDER BY FEE DESC, c.CAR_TYPE ASC, c.CAR_ID DESC;