-- 코드를 입력하세요
SELECT O.ANIMAL_ID,
    O.ANIMAL_TYPE,
    O.NAME
FROM ANIMAL_OUTS O
INNER JOIN ANIMAL_INS I
ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE I.SEX_UPON_INTAKE LIKE 'Intact%'
AND (O.SEX_UPON_OUTCOME LIKE 'Neutered%'
OR O.SEX_UPON_OUTCOME LIKE 'Spayed%')
ORDER BY O.ANIMAL_ID ASC;