-- 코드를 입력하세요
SELECT u.USER_ID,
    u.NICKNAME,
    CONCAT(CITY,' ',STREET_ADDRESS1,' ',STREET_ADDRESS2) AS 전체주소,
    CONCAT(LEFT(u.TLNO,3),'-',SUBSTRING(u.TLNO,4,4),'-',RIGHT(u.TLNO,4)) AS 전화번호
FROM USED_GOODS_BOARD b
LEFT JOIN USED_GOODS_USER u
ON b.WRITER_ID = u.USER_ID
GROUP BY b.WRITER_ID
HAVING COUNT(b.WRITER_ID) >= 3
ORDER BY u.USER_ID DESC;


# SELECT WRITER_ID
# FROM USED_GOODS_BOARD
# GROUP BY WRITER_ID
# HAVING COUNT(WRITER_ID) >= 3;