-- 코드를 입력하세요
SELECT H.FLAVOR
FROM FIRST_HALF H
LEFT JOIN (SELECT FLAVOR,
            SUM(TOTAL_ORDER) AS TOTAL_ORDER
            FROM JULY
            GROUP BY FLAVOR) J
ON H.FLAVOR = J.FLAVOR
ORDER BY H.TOTAL_ORDER + J.TOTAL_ORDER DESC
LIMIT 3;