-- 코드를 입력하세요
SELECT 
    b.CATEGORY,
    SUM(s.SALES) AS TOTAL_SALES
FROM BOOK_SALES s
LEFT JOIN BOOK b
ON s.BOOK_ID = b.BOOK_ID
WHERE SALES_DATE LIKE '2022-01%'
GROUP BY b.CATEGORY
ORDER BY b.CATEGORY ASC;