-- 코드를 입력하세요
SELECT CH.HISTORY_ID,
       ROUND((DATEDIFF(CH.END_DATE,CH.START_DATE)+1) *
        (CASE
            WHEN DATEDIFF(CH.END_DATE,CH.START_DATE)+1 < 7 THEN 1
            WHEN DATEDIFF(CH.END_DATE,CH.START_DATE)+1 < 30 THEN 0.95
            WHEN DATEDIFF(CH.END_DATE,CH.START_DATE)+1 < 90 THEN 0.92
            ELSE 0.85
         END) * CC.DAILY_FEE, 0) AS FEE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY CH
LEFT JOIN CAR_RENTAL_COMPANY_CAR CC
ON CH.CAR_ID = CC.CAR_ID
WHERE CC.CAR_TYPE = '트럭'
ORDER BY FEE DESC, CH.HISTORY_ID DESC;