-- 코드를 입력하세요
WITH SUB_DISCOUNT AS (
    SELECT
        HISTORY_ID,
        CAR_TYPE,
        DAILY_FEE*(DATEDIFF(END_DATE,START_DATE)+1) AS TOTAL_DAILY_FEE,
        CASE
        WHEN DATEDIFF(END_DATE,START_DATE)+1 < 7 THEN '할인없음'
        WHEN DATEDIFF(END_DATE,START_DATE)+1 >= 7 AND DATEDIFF(END_DATE,START_DATE)+1 < 30 THEN '7일 이상'
        WHEN DATEDIFF(END_DATE,START_DATE)+1 >= 30 AND DATEDIFF(END_DATE,START_DATE)+1 < 90 THEN '30일 이상'
        WHEN DATEDIFF(END_DATE,START_DATE)+1 >= 90 THEN '90일 이상'
        END DURATION_TYPE  
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS CH
    LEFT JOIN CAR_RENTAL_COMPANY_CAR AS CC
    ON CH.CAR_ID = CC.CAR_ID
    WHERE CAR_TYPE = '트럭'
)

SELECT 
    HISTORY_ID,
    ROUND(TOTAL_DAILY_FEE * (100-IF(DISCOUNT_RATE IS NULL,0,DISCOUNT_RATE))*0.01) AS FEE
FROM SUB_DISCOUNT AS SD
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS CP
ON SD.CAR_TYPE = CP.CAR_TYPE AND SD.DURATION_TYPE = CP.DURATION_TYPE
ORDER BY FEE DESC, CH.HISTORY_ID DESC;



# SELECT CH.HISTORY_ID,
#        ROUND((DATEDIFF(CH.END_DATE,CH.START_DATE)+1) *
#         (CASE
#             WHEN DATEDIFF(CH.END_DATE,CH.START_DATE)+1 < 7 THEN 1
#             WHEN DATEDIFF(CH.END_DATE,CH.START_DATE)+1 < 30 THEN 0.95
#             WHEN DATEDIFF(CH.END_DATE,CH.START_DATE)+1 < 90 THEN 0.92
#             ELSE 0.85
#          END) * CC.DAILY_FEE, 0) AS FEE
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY CH
# LEFT JOIN CAR_RENTAL_COMPANY_CAR CC
# ON CH.CAR_ID = CC.CAR_ID
# WHERE CC.CAR_TYPE = '트럭'
# ORDER BY FEE DESC, CH.HISTORY_ID DESC;