-- 코드를 입력하세요
SELECT P.PRODUCT_ID,
    P.PRODUCT_NAME,
    SUM(AMOUNT) * P.PRICE AS TOTAL_SALES
FROM FOOD_ORDER O
INNER JOIN FOOD_PRODUCT P
ON O.PRODUCT_ID = P.PRODUCT_ID
WHERE O.PRODUCE_DATE LIKE '2022-05%'
GROUP BY P.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, P.PRODUCT_ID ASC;