-- 코드를 입력하세요
SELECT DISTINCT(h.CAR_ID) AS CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY h
LEFT JOIN CAR_RENTAL_COMPANY_CAR c
ON h.CAR_ID = c.CAR_ID
WHERE c.CAR_TYPE = '세단' 
AND DATE_FORMAT(h.START_DATE,'%m') = '10'
ORDER BY c.CAR_ID DESC;